from tkinter import *

master = Tk()
Label(master,text="Meeting Sheduled",justify='center').grid(row=0,column=3)
Label(master, text='Meeting ID').grid(row=1)
Label(master, text='Agenda').grid(row=2)
Label(master, text='Date').grid(row=3)
Label(master, text='Time').grid(row=4)
Label(master, text='Meeting Type').grid(row=5)
Label(master, text='Meeting Location').grid(row=6)
e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5= Entry(master)
e6 = Entry(master)

e1.grid(row=1, column=1)
e2.grid(row=2, column=1)
e3.grid(row=3, column=1)
e4.grid(row=4, column=1)
e5.grid(row=5, column=1)
e6.grid(row=6, column=1)
mainloop()