from tkinter import *

master = Tk()
Label(master,text="Personal DEtials",justify='center').grid(row=0,column=3)
Label(master, text='First Name').grid(row=1)
Label(master, text='Age').grid(row=2)
Label(master, text='roll number').grid(row=3)
Label(master, text='Last Name').grid(row=4)
e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e1.grid(row=1, column=1)
e2.grid(row=2, column=1)
e3.grid(row=3, column=1)
e4.grid(row=4, column=1)
mainloop()
